// Generated by CoffeeScript 1.9.1
(function() {
  var teachers;

  teachers = {
    teacher: {
      name: "Andrew Chalkley",
      hair: "Ginger"
    },
    teacher: {
      name: "Jim Hoskins",
      hair: "Ginger"
    },
    teacher: {
      name: "Pasan Premaratne",
      hair: "Black"
    }
  };

}).call(this);

//# sourceMappingURL=activities.js.map
